### PR TITLE
refactoring new scraper and new parser into new dir

### PR DESCRIPTION
**Pull request by will-horning**
Hey guys, just merging me and Wes' new code into one directory, take a look and see if this is a good project structure for now (not exactly complicated).

### CODE REVIEW

**Review by bdewilde — COMMENTED** [review]
This seems generally fine. One big question:

How are mods.xml files related to crec files, exactly? Do we want to parse them both in this module, or in separate modules? If separately, should this file be parse_mods.py or something, as Wes originally had it?

And a couple more stylistic comments:

- You could do away with some extra whitespace. For example, there shouldn't be an empty line between docstrings and the related code.
- There are a few spots where variables are single letters rather than descriptive names, which can make following the logic more work.
- In docstrings, you don't need to preface builtin types with `:obj:`, you can just do e.g. `str`
- How interested are you in making this Py2/3 compatible? I would advocate strongly for Py3 code, with optional Py2 compatibility. I would also be more than happy to convert code for you.

**Comment by will-horning** [comment]
@bdewilde 
1. whitespace is mostly from me stripping out the bill scraper parts, I'll clean it up. The rest I can blame on Wes (people on vacation always make good scapegoats).
2. I tend to use single letter variables where its obvious what it is from the context, specifically, any kind of short block with binding at the beginning (for loops, context managers). In those cases, I think that verbosity makes it less readable.
3. Did not know that, it'll still render correctly in sphinx? (link to the Python core docs).
4. We agreed on doing this in Python 3, but we aren't going to be deploying any Python code anytime soon, so I wouldn't say its a priority for this week. As for converting it if necessary, I'll take care of that, I need the Python 3 experience. The only live service we'll currently be running is elasticsearch.

**Comment by will-horning** [comment]
@bdewilde Forgot your first question. The CREC files are published in a zip file once a day (only if congress was in session the previous day). That just contains the raw text content of the documents for that day, the metadata is contained in that mods.xml file (there are record specific mods files for each doc, but not in bulk, we'd have to send a request for each one and the GPO servers do not like handling 100 requests for every day since 1994). 

Since the CREC files are just raw data (there is some xml, but only for display formatting), there is no need to parse them. The reason both parts are in one module is because its main function is to match the doc specific metadata in the mods.xml file with the CREC file it refers to, extract that metadata, format it for elastic search, then upload the CREC doc with the extracted mods.xml metadata for that doc attached.

**Comment by bdewilde** [comment]
@will-horning 

Yes, `str` or `list` as a docstring type should still link out to the python docs. I try to follow the `typing` module's styling for things like a list of strings (`List[str]`), but those don't seem to work in sphinx. I don't know why. :/

Yup, the single-letter variable thing is fine in those contexts, but there were a couple spots in the code where I had to squint real hard at them to make sure I followed what was happening. No big deal tho.

If the CREC files don't need to be parsed, what in the world is [this module](https://github.com/chartbeat-labs/Capitol-Words/blob/master/parser/parser.py) for?

**Comment by will-horning** [comment]
@bdewilde That is the old parser. I believe the reason its doing that is because solr doesn't support n-gram search like elasticsearch. I'm grasping at straws here, this project has gone through so many iterations that we've decided to abandon the old code (its been hacked together off and on since Chartbeat's only product was Firefly). So its basically a teardown at this point.

Those regexes might be useful however in understanding the formal legalese a lot of these documents are written in. So, while there is no need for parsing in the sense of unpacking data in a serialized format, we could potentially find some value in parsing the text itself.

**Pull request closed without merging**
