### PR TITLE
Clean Up Imports and Settings Files

### PR DESCRIPTION
**Pull request by ackramer**
Hey Y'all,

This is mostly a cleanup PR for some imports and the `settings.py` files littering the repo.

1) Rename the top-level, non-django `settings.py` file to `environment.py`. It's clearly not a django file and shouldn't be confused with one. Now we just have `settings.py`, `local_settings.py` and `local_settings.example.py` under `/cwod_site`.
2) Remove symlinks to the top level `settings.py` (now `environment.py`) file in the solr, ingest, and parser directories. I think the original environment had python path issues so they used symlinks to fake it. They're not needed, we can import directly from `environment.py`
3) Get rid of import * from the files I modified that import environment ... devil be gone! Also bring imports to pep8 and remove unused imports.
4) Cleaned up several constant imports from settings/environment that were undefined.  I don't know what the values should be for all these variables but I have made educated guesses. These include: `SOLR_DOC_PATH`, `DB_PATH`, `DB_PARAMS`, and `BIOGUIDE_LOOKUP_PATH`. These variables are all unrelated to each other and refer to separate data sources. `DB_PATH` points to an unknown sqllite database. `DB_PARAMS` is used to connect to the Django MySQL directly instead of using the ORM. `BIOGUIDE_LOOKUP_PATH` points to a file with pipe-separated bio data about legislators. Lastly, `SOLR_DOC_PATH` seems to point to a directory where debug output (I think) is placed before writing to solr in the ingester.
5) Clean up solr lib DB imports, now included in environment.py. Some of these variables, as mentioned in 4), were previously undefined and point to data we don't have in the repo e.g. `DB_PATH` and `BIOGUIDE_LOOKUP_PATH`. `BIOGUIDE_LOOKUP_PATH` doesn't look like it's strictly required (it seems to be used as a backup source for data). `DB_PATH` on the other hand is used to connect to a sqllite database that is mentioned no where in the code base other than when we try to connect to it in `solr/lib.py:volume_lookup(...)`. This is still a mystery to me. Since we don't have data about these two variables I have set them to `/dev/null` for now. 

@will-horning @rmangi @manny

### CODE REVIEW

**Comment by ackramer** [comment]
Just pushed a commit which actually fixes the issue with being able to import from the toplevel settings.py/environment.py which led someone to create the symlinks. I thought I had fixed and I hadn't, still couldn't import. I had to add /cwod to the python path. I thought it would already be importable but I guess not.

**Comment by ackramer** [comment]
Also added export to Vagrantfile for `export DJANGO_MODULE_SETTINGS=cwod_site.settings` so environment.py can rely on it (DB_PARAMS uses the Django settings for the MySQL so we can directly connect without the ORM).

**Comment by rmangi** [comment]
LGTM

**Comment by ackramer** [comment]
Note: merging this now, you may need to re-provision your VM!

**Pull request merged**
